PUT http://ihm-api.test/user/edit
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "session_token": "$2y$10$uefNZ7goiIm.D4G.MKqdNOe5sgBSuXJ62MYifAAqdUy4d5NjorCvy",
    "password": "test",
    "name": "Farino"
}

###
DELETE http://ihm-api.test/user/delete
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "session_token": "$2y$10$uefNZ7goiIm.D4G.MKqdNOe5sgBSuXJ62MYifAAqdUy4d5NjorCvy",
    "password": "test"
}

###
POST http://ihm-api.test/user/register
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farineau@gmail.com",
    "password": "test",
    "password_confirm": "test",
    "name": "Farineau",
    "firstname": "Thomas"
}

###
POST http://ihm-api.test/user/register
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farineau@gmail.com",
    "password": "test",
    "password_confirm": "test",
    "name": "Farineau",
    "firstname": "Thomas"
}

###
POST http://ihm-api.test/user/register
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farineau@icloud.com",
    "password": "test",
    "password_confirm": "testa",
    "name": "test",
    "firstname": "test"
}

###
POST http://ihm-api.test/user/register
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farineau@icloud.com"
}

###
POST http://ihm-api.test/user/login
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farineau@icloud.com"
}

###
POST http://ihm-api.test/user/login
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farinepau@icloud.com",
    "password": "1234"
}

###
POST http://ihm-api.test/user/login
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farineau@icloud.com",
    "password": "1234"
}

###
POST http://ihm-api.test/user/login
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "thomas.farineau@icloud.com",
    "password": "oui"
}

###
POST http://ihm-api.test/user/login
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "email": "oui",
    "password": "oui"
}

###
POST http://ihm-api.test/user
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "session_token": "oui"
}

###
POST http://ihm-api.test/user
Content-Type: application/json

{
    "token": "bleruheibuari",
    "session_token": "oui"
}

###
POST http://ihm-api.test/user
Content-Type: application/json

{
    "token": "Y2VjaSBlc3QgdW5lIHBhdGF0ZSBkb3VjZQ==",
    "session_token": null
}

###
GET http://ihm-api.test/user/1
Accept: application/json

###
GET http://ihm-api.test/user/2000
Accept: application/json

###
